creating data

In [36]:
import pandas as pd

In [37]:
#series=1 dimensional
colours=pd.Series(['red','black','white'])
colours

0      red
1    black
2    white
dtype: str

In [ ]:
#data frame = 2D
data={
    'name':['ram','hari','shyam'],
    'age':[20,25,30],
    'city':['kathmandu','lalitpur','bhaktapur']
}

df=pd.DataFrame(data,columns=['name','age','city'])
print(df)
#saving to csv
df.to_csv('output.csv', index=False)#removes index

    name  age       city
0    ram   20  kathmandu
1   hari   25   lalitpur
2  shyam   30  bhaktapur

reading files

In [35]:
car_sales=pd.read_csv('car-sales.csv')
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [18]:
car_sales.to_csv('exported-car.csv',index=False)

In [23]:
exported_car=pd.read_csv('exported-car.csv')
exported_car

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

data types

In [25]:
#attributes 
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

column operation

In [39]:

# Display column namescar_sales.columns
car_sales.columns
# Select single column
car_sales["Make"]
# Select multiple columns
car_sales[["Make", "Price"]]

     Make       Price
0  Toyota   $4,000.00
1   Honda   $5,000.00
2  Toyota   $7,000.00
3     BMW  $22,000.00
4  Nissan   $3,500.00
5  Toyota   $4,500.00
6   Honda   $7,500.00
7   Honda   $7,000.00
8  Toyota   $6,250.00
9  Nissan   $9,700.00

viewing data

In [27]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [30]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [32]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [33]:
car_sales.head(5)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [34]:
car_sales.tail(3)

     Make Colour  Odometer (KM)  Doors      Price
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

Data Analysis

In [41]:
# Most common car brand
car_sales["Make"].value_counts()

Make
Toyota    4
Honda     3
Nissan    2
BMW       1
Name: count, dtype: int64

sorting dataset

In [42]:
# Sort by price
car_sales.sort_values("Price")

     Make Colour  Odometer (KM)  Doors       Price
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
0  Toyota  White         150043      4   $4,000.00
5  Toyota  Green          99213      4   $4,500.00
1   Honda    Red          87899      4   $5,000.00
8  Toyota  White          60000      4   $6,250.00
2  Toyota   Blue          32549      3   $7,000.00
7   Honda   Blue          54738      4   $7,000.00
6   Honda   Blue          45698      4   $7,500.00
9  Nissan  White          31600      4   $9,700.00